-- MySQL Script generated by MySQL Workbench
-- Thu May  5 15:56:59 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema scorepoint
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `scorepoint` ;

-- -----------------------------------------------------
-- Schema scorepoint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scorepoint` DEFAULT CHARACTER SET latin1 ;
USE `scorepoint` ;

-- -----------------------------------------------------
-- Table `scorepoint`.`ACL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`ACL` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`ACL` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(512) NULL DEFAULT NULL,
  `property` VARCHAR(512) NULL DEFAULT NULL,
  `accessType` VARCHAR(512) NULL DEFAULT NULL,
  `permission` VARCHAR(512) NULL DEFAULT NULL,
  `principalType` VARCHAR(512) NULL DEFAULT NULL,
  `principalId` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `scorepoint`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`Role` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`Role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(512) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `scorepoint`.`RoleMapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`RoleMapping` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`RoleMapping` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `principalType` VARCHAR(512) NULL DEFAULT NULL,
  `principalId` VARCHAR(512) NULL DEFAULT NULL,
  `roleId` INT(11) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_RoleMapping_Role1`
    FOREIGN KEY (`roleId`)
    REFERENCES `scorepoint`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_RoleMapping_Role1_idx` ON `scorepoint`.`RoleMapping` (`roleId` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`user` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `realm` VARCHAR(512) NULL DEFAULT NULL,
  `username` VARCHAR(512) NULL DEFAULT NULL,
  `password` VARCHAR(512) NOT NULL,
  `credentials` TEXT NULL DEFAULT NULL,
  `challenges` TEXT NULL DEFAULT NULL,
  `email` VARCHAR(512) NOT NULL,
  `emailVerified` TINYINT(1) NULL DEFAULT NULL,
  `verificationToken` VARCHAR(512) NULL DEFAULT NULL,
  `status` VARCHAR(512) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `lastUpdated` DATETIME NULL DEFAULT NULL,
  `initialRank` INT NULL DEFAULT 0,
  `imageUrl` VARCHAR(255) NULL,
  `firstName` VARCHAR(2555) NULL,
  `lastName` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `scorepoint`.`accessToken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`accessToken` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`accessToken` (
  `id` VARCHAR(255) NOT NULL,
  `ttl` INT(11) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `userid` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_accessToken_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `scorepoint`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_accessToken_user1_idx` ON `scorepoint`.`accessToken` (`userid` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`tournament` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`tournament` (
  `tournamentId` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL DEFAULT NULL,
  `pointValue` INT(11) NOT NULL,
  PRIMARY KEY (`tournamentId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `name_UNIQUE` ON `scorepoint`.`tournament` (`name` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`I`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`lobby` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`lobby` (
  `lobbyId` INT(11) NOT NULL AUTO_INCREMENT,
  `active` BIT(1) NOT NULL DEFAULT b'1' COMMENT 'The User Team table enable to support a team',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tournament_tournamentId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`lobbyId`),
  CONSTRAINT `fk_game_tournament1`
    FOREIGN KEY (`tournament_tournamentId`)
    REFERENCES `scorepoint`.`tournament` (`tournamentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_game_tournament1_idx` ON `scorepoint`.`I` (`tournament_tournamentId` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`team` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`team` (
  `idTeam` INT(11) NOT NULL AUTO_INCREMENT,
  `pair` BIT(1) NOT NULL DEFAULT b'0' COMMENT 'the teams is of two people?',
  `active` BIT(1) NOT NULL DEFAULT b'1',
  `lobbyId` INT(11) NOT NULL,
  PRIMARY KEY (`idTeam`),
  CONSTRAINT `fk_team_game1`
    FOREIGN KEY (`lobbyId`)
    REFERENCES `scorepoint`.`I` (`lobbyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_team_game1_idx` ON `scorepoint`.`team` (`lobbyId` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`challenge_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`challenge_request` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`challenge_request` (
  `challenge_requestid` INT(11) NOT NULL AUTO_INCREMENT,
  `challenger_id` INT(11) NOT NULL COMMENT 'The team who is challenging to other ',
  `victim_id` INT(11) NOT NULL COMMENT 'the victim will be destroyed',
  PRIMARY KEY (`challenge_requestid`),
  CONSTRAINT `fk_challenge_request_team1`
    FOREIGN KEY (`challenger_id`)
    REFERENCES `scorepoint`.`team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_challenge_request_team2`
    FOREIGN KEY (`victim_id`)
    REFERENCES `scorepoint`.`team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_challenge_request_team1_idx` ON `scorepoint`.`challenge_request` (`challenger_id` ASC);

CREATE INDEX `fk_challenge_request_team2_idx` ON `scorepoint`.`challenge_request` (`victim_id` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`match` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`match` (
  `idmatch` INT(11) NOT NULL AUTO_INCREMENT,
  `started` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Lobby_lobbyId` INT(11) NOT NULL,
  PRIMARY KEY (`idmatch`),
  CONSTRAINT `fk_match_Lobby1`
    FOREIGN KEY (`Lobby_lobbyId`)
    REFERENCES `scorepoint`.`I` (`lobbyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_match_Lobby1_idx` ON `scorepoint`.`match` (`Lobby_lobbyId` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`game` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`game` (
  `gameId` INT(11) NOT NULL AUTO_INCREMENT,
  `order` INT(11) NULL DEFAULT NULL,
  `idmatch` INT(11) NOT NULL,
  `teamWinnerId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`gameId`),
  CONSTRAINT `fk_set_match1`
    FOREIGN KEY (`idmatch`)
    REFERENCES `scorepoint`.`match` (`idmatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_set_team1`
    FOREIGN KEY (`teamWinnerId`)
    REFERENCES `scorepoint`.`team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_set_match1_idx` ON `scorepoint`.`game` (`idmatch` ASC);

CREATE INDEX `fk_set_team1_idx` ON `scorepoint`.`game` (`teamWinnerId` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`teamRequest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`teamRequest` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`teamRequest` (
  `idteamRequest` INT(11) NOT NULL,
  `user_emiter` INT(11) NOT NULL,
  `user_receptor` INT(11) NOT NULL,
  `datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idteamRequest`),
  CONSTRAINT `fk_teamRequest_user1`
    FOREIGN KEY (`user_emiter`)
    REFERENCES `scorepoint`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teamRequest_user2`
    FOREIGN KEY (`user_receptor`)
    REFERENCES `scorepoint`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_teamRequest_user1_idx` ON `scorepoint`.`teamRequest` (`user_emiter` ASC);

CREATE INDEX `fk_teamRequest_user2_idx` ON `scorepoint`.`teamRequest` (`user_receptor` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`teamSetScore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`teamSetScore` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`teamSetScore` (
  `playerSetScroreId` INT(11) NOT NULL AUTO_INCREMENT,
  `score` INT(11) NOT NULL DEFAULT '0',
  `set_setId` INT(11) NOT NULL,
  `team_idTeam` INT(11) NOT NULL,
  PRIMARY KEY (`playerSetScroreId`),
  CONSTRAINT `fk_teamSetScore_set1`
    FOREIGN KEY (`set_setId`)
    REFERENCES `scorepoint`.`game` (`gameId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teamSetScore_team1`
    FOREIGN KEY (`team_idTeam`)
    REFERENCES `scorepoint`.`team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_teamSetScore_set1_idx` ON `scorepoint`.`teamSetScore` (`set_setId` ASC);

CREATE INDEX `fk_teamSetScore_team1_idx` ON `scorepoint`.`teamSetScore` (`team_idTeam` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`team_has_match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`team_has_match` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`team_has_match` (
  `idTeam` INT(11) NOT NULL,
  `idmatch` INT(11) NOT NULL,
  PRIMARY KEY (`idTeam`, `idmatch`),
  CONSTRAINT `fk_team_has_match_match1`
    FOREIGN KEY (`idmatch`)
    REFERENCES `scorepoint`.`match` (`idmatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_match_team1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `scorepoint`.`team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_team_has_match_match1_idx` ON `scorepoint`.`team_has_match` (`idmatch` ASC);

CREATE INDEX `fk_team_has_match_team1_idx` ON `scorepoint`.`team_has_match` (`idTeam` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`userCredential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`userCredential` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`userCredential` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `provider` VARCHAR(512) NULL DEFAULT NULL,
  `authScheme` VARCHAR(512) NULL DEFAULT NULL,
  `externalId` VARCHAR(512) NULL DEFAULT NULL,
  `profile` TEXT NULL DEFAULT NULL,
  `credentials` TEXT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `userid` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_userCredential_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `scorepoint`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_userCredential_user1_idx` ON `scorepoint`.`userCredential` (`userid` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`userIdentity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`userIdentity` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`userIdentity` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `provider` VARCHAR(512) NULL DEFAULT NULL,
  `authScheme` VARCHAR(512) NULL DEFAULT NULL,
  `externalId` VARCHAR(512) NULL DEFAULT NULL,
  `profile` TEXT NULL DEFAULT NULL,
  `credentials` TEXT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `userid` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_userIdentity_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `scorepoint`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_userIdentity_user1_idx` ON `scorepoint`.`userIdentity` (`userid` ASC);


-- -----------------------------------------------------
-- Table `scorepoint`.`user_has_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scorepoint`.`user_has_team` ;

CREATE TABLE IF NOT EXISTS `scorepoint`.`user_has_team` (
  `userid` INT(11) NOT NULL,
  `idTeam` INT(11) NOT NULL,
  PRIMARY KEY (`userid`, `idTeam`),
  CONSTRAINT `fk_user_has_team_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `scorepoint`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_team_team1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `scorepoint`.`team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_user_has_team_team1_idx` ON `scorepoint`.`user_has_team` (`idTeam` ASC);

CREATE INDEX `fk_user_has_team_user1_idx` ON `scorepoint`.`user_has_team` (`userid` ASC);

USE `scorepoint` ;

-- -----------------------------------------------------
-- Placeholder table for view `scorepoint`.`user_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scorepoint`.`user_stats` (`id` INT, `userName` INT, `gameId` INT, `total_sets` INT, `winner_sets` INT);

-- -----------------------------------------------------
-- View `scorepoint`.`user_stats`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `scorepoint`.`user_stats` ;
DROP TABLE IF EXISTS `scorepoint`.`user_stats`;
USE `scorepoint`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `scorepoint`.`user_stats` AS
select `u`.`id` AS `id`,`u`.`userName` AS `userName`,
`g`.`gameId` AS `gameId`,
count(`s`.`setId`) AS `total_sets`,
sum(if((`s`.`teamWinnerId` = `t`.`idTeam`),1,0)) AS `winner_sets`
from ((((((`scorepoint`.`user` `u` join `scorepoint`.`user_has_team` `u_t` on((`u`.`id` = `u_t`.`userid`))) join `scorepoint`.`team` `t` on((`u_t`.`idTeam` = `t`.`idTeam`))) join `scorepoint`.`game` `g` on((`t`.`gameId` = `g`.`gameId`))) join `scorepoint`.`team_has_match` `t_m` on((`t`.`idTeam` = `t_m`.`idTeam`))) join `scorepoint`.`match` `m` on((`t_m`.`idmatch` = `m`.`idmatch`))) join `scorepoint`.`set` `s` on((`m`.`idmatch` = `s`.`idmatch`))) group by `m`.`idmatch`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
